const drawingPrompts = [
  "Circle",
  "Square",
  "Triangle",
  "Rectangle",
  "Wavy line",
  "Zigzag",
  "Spiral",
  "Cross",
  "Smiley face",
  "Heart",
  "Sun",
  "Moon",
  "Cloud",
  "Star",
  "Arrow",
  "Leaf",
  "Flower petal",
  "Raindrop",
  "Ice cream cone",
  "Tree trunk",
  "Stick figure",
  "Mountain",
  "Cup",
  "Apple",
  "House outline",
  "Snowflake",
  "Fish",
  "Balloon",
  "Tree",
  "Cactus",
  "Chair",
  "Table",
  "Book",
  "Pencil",
  "Hand",
  "Foot",
  "Bird",
  "Butterfly",
  "Car",
  "Boat",
  "Rocket",
  "Castle",
  "Face profile",
  "Eye",
  "Nose",
  "Mouth",
  "Ear",
  "Horse",
  "Cat",
  "Dog",
  "Spoon",
  "Fork",
  "Knife",
  "Plate",
  "Cupcake",
  "Door",
  "Window frame",
  "Guitar",
  "Keyboard",
  "Laptop",
  "Smartphone",
  "Headphones",
  "Umbrella",
  "Lamp",
  "Sofa",
  "Bookshelf",
  "Clock",
  "Backpack",
  "Airplane",
  "Bench",
  "Fence",
  "Mailbox",
  "Cup of coffee",
  "Ice cube",
  "Chocolate bar",
  "Donut",
  "Water bottle",
  "Candle",
  "Lollipop",
  "Straw",
  "Paper airplane",
  "Paper crane",
  "Bookmark",
  "Pushpin",
  "Lightbulb",
  "Fountain pen",
  "Rubber band",
  "Scissors",
  "Tape dispenser",
  "Spool of thread",
  "Button",
  "Toothbrush",
  "Toothpaste",
  "Shampoo bottle",
  "Bar of soap",
  "Hand sanitizer",
  "Nail polish",
  "Perfume bottle",
  "Lotion bottle",
  "Cotton swabs",
  "Cotton balls",
  "Thermometer",
  "Band-aid",
  "Vitamins",
  "Medicine bottle",
  "Tissues",
  "Shaving razor",
  "Shaving cream",
  "Comb",
  "Brush",
  "Mirror",
  "Scalp massager",
  "Hairdryer",
  "Curtain",
  "Fan",
  "Coat hanger",
  "Towel",
  "Bathrobe",
  "Slippers",
  "Umbrella handle",
  "Rain boots",
  "Hoodie",
  "Sweatshirt",
  "Glasses case",
  "Sunglasses",
  "Scarf knot",
  "Backpack zipper",
  "Suitcase",
  "Sleeping mask",
  "Earplugs",
  "Thermal flask",
  "Earbuds",
  "Charger",
  "Extension cord",
  "Light switch",
  "Doorknob",
  "Tissues box",
  "Coaster",
  "Corkboard",
  "Notepad",
  "Sticky notes",
  "Pen holder",
  "Magnifying glass",
  "Calculator",
  "Stapler",
  "Paperclip",
  "Notebook",
  "Drawing compass",
  "Binder clips",
  "Letter opener",
  "Mail envelope",
  "Stamp",
  "Sticky note",
  "Sharpener",
  "Ruler",
  "Eraser",
  "Clipboard",
  "Clipboard with paper",
  "Filing cabinet",
  "Pushpin map",
  "Wall clock",
  "Corkboard pin",
  "Magnifying lens",
  "Shovel",
  "Trowel",
  "Worm",
  "Ant",
  "Ladybug",
  "Spider web",
  "Caterpillar",
  "Moth",
  "Dragonfly",
  "Bee hive",
  "Snail",
  "Firefly",
  "Grasshopper",
  "Ant hill",
  "Worms in soil",
  "Climbing vine",
  "Butterfly wings",
  "Hummingbird",
  "Nest with eggs",
  "Bees buzzing",
  "Acorn",
  "Dandelion",
  "Tree rings",
  "Fern leaf",
  "Cactus flower",
  "Cherry blossom",
  "Sunflower field",
  "Pine tree branches",
  "Pine needles",
  "Pumpkin patch",
  "Sunflower stem",
  "Tropical fish",
  "Seahorse",
  "Jellyfish",
  "Crab",
  "Octopus",
  "Coral",
  "Seaweed",
  "Clams",
  "Mussels",
  "Starfish arm",
  "Shark fin",
  "Mermaid tail",
  "Whale tail",
  "Anglerfish",
  "Lobster",
  "Koi fish",
  "Swan",
  "Penguin",
  "Seal",
  "Dolphin",
  "Streetlight",
  "Train",
  "Bicycle",
  "Truck",
  "Bus",
  "Motorcycle",
  "Basketball",
  "Soccer ball",
  "Baseball glove",
  "Football helmet",
  "Palm tree",
  "Mountain range",
  "River",
  "Waterfall",
  "Sunset",
  "Starfish",
  "Shell",
  "Flower",
  "Bee",
  "Banana",
  "Strawberry",
  "Lemon",
  "Pear",
  "Grapes",
  "Pineapple",
  "Mushroom",
  "Corn",
  "Carrot",
  "Broccoli",
  "Hot air balloon",
  "Kite",
  "Swing",
  "Campfire",
  "Flashlight",
  "Snowman",
  "Scarf",
  "Hat",
  "Gloves",
  "Bow tie",
  "Necklace",
  "Ring",
  "Bag",
  "Wallet",
  "Shoes",
  "Boots",
  "Basket",
  "Egg",
  "Pancake",
  "Pizza slice",
  "Burger",
  "Fries",
  "Sandwich",
  "Sushi",
  "Pinecone",
  "Cup of tea",
  "Mug",
  "Bottle",
  "Vase",
  "Ladder",
  "Hammer",
  "Wrench",
  "Screwdriver",
  "Paintbrush",
  "Palette",
  "Compass",
  "Globe",
  "Map",
  "Key",
  "Lock",
  "Lantern",
  "Binoculars",
  "Camera",
  "Clock",
  "Dice",
  "Chess piece",
  "Ball",
  "Drum",
  "Guitar",
  "Violin",
  "Flute",
  "Tambourine",
  "Cupcake",
  "Bow",
  "Feather",
  "Glasses",
  "Star cluster",
  "Bookmark",
  "Envelope",
  "Trophy",
  "Fan",
  "Medal",
  "Telescope",
  "Pinecone",
  "Detailed tree",
  "Forest path",
  "Park scene",
  "Living room",
  "Kitchen interior",
  "Bathroom interior",
  "Bedroom interior",
  "Office setup",
  "Character full body",
  "Walking pose",
  "Running pose",
  "Jumping pose",
  "Dancing pose",
  "Horse in motion",
  "Car from side view",
  "Car from front view",
  "Bicycle with rider",
  "Airplane in flight",
  "City skyline at night",
  "Planet with moon",
  "Volcano erupting",
  "Lighthouse on shore",
  "Desert scene",
  "Rainy street",
  "Snowy forest",
  "Wolf howling",
  "Eagle in flight",
  "Tiger in jungle",
  "Elephant in savannah",
  "Lion roaring",
  "Whale underwater",
  "Underwater reef",
  "School of fish",
  "City market",
  "People at café",
  "Fireworks in sky",
  "Circus tent",
  "Roller coaster",
  "Space station",
  "Astronaut",
  "Camping scene",
  "Ocean waves",
  "Moonlit sky",
  "Bird flock",
  "Horse grazing",
  "Market stalls",
  "Family picnic",
  "Ancient ruins",
  "Fantasy castle",
  "Futuristic vehicle",
  "Battle scene",
  "Alien landscape",
  "Spaceship interior",
  "Robot",
  "Steampunk glasses",
  "Greek temple",
  "Roman colosseum",
  "Mountain village",
  "Camping site",
  "Forest with animals",
  "Tropical island",
  "Savannah wildlife",
  "Polar landscape",
  "Sci-fi character",
  "Robot battle",
  "Dragon atop mountain",
  "Warrior in armor",
  "Giant robot",
];

let promptElement;

function loadPrompt() {
    const savedDay = localStorage.getItem("currentDay");
    promptElement = document.getElementById("prompt");

    if (savedDay !== null) {
      const index = parseInt(savedDay, 10);
      promptElement.textContent = drawingPrompts[index];
    } else {
      promptElement.textContent = drawingPrompts[0];
    }
}

function saveDay() {
    const latestDay = parseInt(document.getElementById("latestDay").value, 10);
    if (!isNaN(latestDay) && latestDay >= 0 && latestDay <= 364) {
      const nextDay = latestDay;
      localStorage.setItem("currentDay", nextDay);
      document.getElementById("prompt").textContent = drawingPrompts[nextDay];
    } else {
      alert("Please enter a valid day number between 0 and 364.");
    }
}

function getRandom() {
    const random = Math.floor(Math.random() * 366);
    promptElement.textContent = drawingPrompts[random];
}

window.onload = loadPrompt;
